/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * login sucessful
 */
export class LogInResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "jwt" })
  jwt: string;
}
