/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Post } from "./post";
import { Expose, Type } from "class-transformer";

/**
 * successful
 */
export class PostResultSet extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count: number;

    @SpeakeasyMetadata()
    @Expose({ name: "pageSize" })
    pageSize: number;

    @SpeakeasyMetadata({ elemType: Post })
    @Expose({ name: "posts" })
    @Type(() => Post)
    posts: Post[];
}
