/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Create a new post
 */
export class PostPostRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description: string;

  @SpeakeasyMetadata()
  @Expose({ name: "link" })
  link: string;

  @SpeakeasyMetadata()
  @Expose({ name: "rootDomain" })
  rootDomain: string;

  @SpeakeasyMetadata()
  @Expose({ name: "title" })
  title: string;
}
